# Generated by Django 4.2.15 on 2024-08-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'News Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('image_slider', 2), ('vision_section', 5), ('latest_news', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Slider Images'}), 2: ('wagtail.blocks.StructBlock', [[('images', 1)]], {}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Vision Text'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Vision Image'}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 4)]], {}), 6: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.NewsPage']}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Latest News'}), 8: ('wagtail.blocks.StructBlock', [[('news', 7)]], {})}, null=True),
        ),
    ]
